#!/usr/bin/env bash
# analyze_castlevania.sh — Complete workflow: Ghidra analysis → TOML config
#
# This script:
# 1. Extracts ARM9/ARM7 binaries from the ROM
# 2. Analyzes them in Ghidra
# 3. Exports function lists
# 4. Converts to TOML format
# 5. Merges into final castlevania_dos.toml
#
# Usage: bash ghidra/analyze_castlevania.sh <GHIDRA_INSTALL_DIR>

set -euo pipefail

GHIDRA="${1:-}"
if [ -z "$GHIDRA" ]; then
    echo "ERROR: Please specify Ghidra installation directory"
    echo "Usage: $0 <GHIDRA_INSTALL_DIR>"
    echo "Example: $0 /home/user/ghidra_11.0"
    exit 2
fi

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
ROM_PATH="/media/windroid/SSD KING/Recomp-NDS/Castlevania - Dawn of Sorrow .nds"
GENERATED_DIR="$REPO_ROOT/generated"
TOOLS_DIR="$REPO_ROOT/tools"

mkdir -p "$GENERATED_DIR"

if [ ! -f "$ROM_PATH" ]; then
    echo "ERROR: ROM not found at $ROM_PATH"
    exit 1
fi

echo "=== Analyzing Castlevania: Dawn of Sorrow with Ghidra ==="
echo "Ghidra: $GHIDRA"
echo "ROM: $ROM_PATH"
echo ""

# Step 1: Import and analyze in Ghidra
echo "Step 1: Importing ROM into Ghidra and analyzing..."
bash "$REPO_ROOT/ghidra/import_castlevania.sh" "$GHIDRA"

if [ ! -f "$GENERATED_DIR/castlevania_function_starts_arm9.json" ] || \
   [ ! -f "$GENERATED_DIR/castlevania_function_starts_arm7.json" ]; then
    echo "ERROR: Ghidra analysis failed - JSON files not generated"
    exit 1
fi

echo "✓ Ghidra analysis complete"
echo ""

# Step 2: Convert JSON to TOML
echo "Step 2: Converting Ghidra exports to TOML format..."

python3 "$TOOLS_DIR/ghidra_to_toml.py" \
    "$GENERATED_DIR/castlevania_function_starts_arm9.json" \
    "$GENERATED_DIR/castlevania_arm9_ghidra.toml" \
    "arm9"

python3 "$TOOLS_DIR/ghidra_to_toml.py" \
    "$GENERATED_DIR/castlevania_function_starts_arm7.json" \
    "$GENERATED_DIR/castlevania_arm7_ghidra.toml" \
    "arm7"

echo "✓ TOML conversion complete"
echo ""

# Step 3: Merge into final config
echo "Step 3: Merging into final castlevania_dos.toml..."

# Create final config with header
cat > "$REPO_ROOT/castlevania_dos.toml" << 'EOF'
# castlevania_dos.toml — recompile config for Castlevania: Dawn of Sorrow
#
# This configuration was generated from Ghidra analysis for maximum reliability.
# SHA-1: 9d4b6f7e4c473954c763d27c59c33f57b8b2f9f9
#
# Generated by: ghidra/analyze_castlevania.sh

[program]
name         = "Castlevania: Dawn of Sorrow"
id           = "castlevania_dos"
cpu          = "arm9"
isa          = "armv5te"
load_address = 0x02000000
size         = 0x04000000
entry_pc     = 0x02000000

[identity]
sha1 = "9d4b6f7e4c473954c763d27c59c33f57b8b2f9f9"

EOF

# Append ARM9 functions
echo "# ── ARM9 Functions (from Ghidra analysis) ────────────────────────" >> "$REPO_ROOT/castlevania_dos.toml"
cat "$GENERATED_DIR/castlevania_arm9_ghidra.toml" >> "$REPO_ROOT/castlevania_dos.toml"

# Append ARM7 functions
echo "" >> "$REPO_ROOT/castlevania_dos.toml"
echo "# ── ARM7 Functions (from Ghidra analysis) ────────────────────────" >> "$REPO_ROOT/castlevania_dos.toml"
cat "$GENERATED_DIR/castlevania_arm7_ghidra.toml" >> "$REPO_ROOT/castlevania_dos.toml"

# Append cartridge config
cat >> "$REPO_ROOT/castlevania_dos.toml" << 'EOF'

# ── Cartridge save configuration ─────────────────────────────────────────
[cartridge]
save_type = "eeprom"
save_size = 65536

# ── Memory regions ────────────────────────────────────────────────────
[[memory_region]]
name = "arm9_itcm"
start = 0x00000000
size = 0x00004000

[[memory_region]]
name = "arm9_dtcm"
start = 0x00004000
size = 0x00004000

[[memory_region]]
name = "main_ram"
start = 0x02000000
size = 0x00400000

[[memory_region]]
name = "arm7_wram"
start = 0x03800000
size = 0x00010000
EOF

echo "✓ Final configuration created: castlevania_dos.toml"
echo ""

# Step 4: Summary
echo "=== Analysis Complete ==="
echo "Generated files:"
echo "  - $GENERATED_DIR/castlevania_function_starts_arm9.json"
echo "  - $GENERATED_DIR/castlevania_function_starts_arm7.json"
echo "  - $GENERATED_DIR/castlevania_arm9_ghidra.toml"
echo "  - $GENERATED_DIR/castlevania_arm7_ghidra.toml"
echo "  - $REPO_ROOT/castlevania_dos.toml (final config)"
echo ""
echo "Next steps:"
echo "  1. Review castlevania_dos.toml"
echo "  2. Run: ./recompile_castlevania.sh"
echo "  3. Test the recompiled game"
